import { MaterialLink } from 'entities/Material';

export default [
  {
    id: '0401e511-bbfe-4a08-88f5-1dbad307d43b',
    name: '▷ Proben Klasse 6 Mittelschule | Catlux',
    tags: [
      '#l',
      '#eintragen',
      '#Rechenarten',
      '#Bruchzahlen',
      '#unregelmäßig',
      '#erkennen',
      '#Punkte',
      '#Gramm',
      '#gemischt',
      '#einfach',
      '#Cent',
      '#einsetzen ausrechnen',
      '#Seiten',
      '#erweitern',
      '#Geometrie',
      '#vor',
      '#Linie',
      '#Euro',
      '#Text',
      '#Viereck',
      '#ganze',
      '#kritisch',
      '#schwierig',
      '#richtig',
      '#Arbeitsblatt',
      '#zwei',
      '#malrechnen',
      '#unterscheiden',
      '#durch',
      '#Test',
      '#Arten',
      '#einordnen',
      '#Veränderung',
      '#Grundrechenarten',
      '#Angaben',
      '#besondere',
      '#dem',
      '#Größen',
      '#nach',
      '#Einführung',
      '#Teile',
      '#Ablesen',
      '#Infos',
      '#Verständnis',
      '#Zahl',
      '#Song',
      '#zu',
      '#viele',
      '#gemischte',
      '#Warum',
      '#Übungen. Dividieren',
      '#drei',
      '#Beispiel',
      '#verwenden',
      '#lassen',
      '#Sachrechnen',
      '#Ergebnisse',
      '#sortieren',
      '#mittel',
      '#Merkmale',
      '#Meinung',
      '#Grammatik Stil',
      '#Begleitsatz',
      '#Mediennutzung',
      '#Ratgeber',
      '#Stichpunkte',
      '#richtig lesen',
      '#kurze Selbstlaute',
      '#Pro',
      '#Medienquiz',
      '#Vers',
      '#Homepage',
      '#kurzes a',
      '#ableiten',
      '#i',
      '#e',
      '#zusammen',
      '#Fremdsprache',
      '#ä oder e',
      '#u',
      '#ll',
      '#Sätze',
      '#suchen',
      '#Informationen',
      '#Verb',
      '#Website',
      '#Formulierungshilfen',
      '#ss',
      '#Aufforderung',
      '#Sachtext',
      '#Zustand',
      '#Informationen finden',
      '#wie stehe ich richtig',
      '#pro',
      '#dividieren',
      '#planen',
      '#mm',
      '#ablesen',
      '#Rechenregeln',
      '#multiplizieren',
      '#Punkt',
      '#Prozent',
      '#Term',
      '#plus',
      '#teilen',
      '#Fragebogen',
      '#Textaufgaben',
      '#geteilt',
      '#verschiedene',
      '#Innenwinkel',
      '#berechnen',
      '#SSW',
      '#lange',
      '#finden',
      '#b oder p',
      '#literarische',
      '#Art und Weise',
      '#Lücken füllen',
      '#Gesprächsregel',
      '#Hauptsätze',
      '#verlängern',
      '#Arbeiten mit Word',
      '#ih',
      '#Ort',
      '#Satzbau',
      '#d oder t',
      '#Empfehlungen',
      '#Fragen',
      '#dass',
      '#Word',
      '#gleich',
      '#wenn',
      '#Inhalt',
      '#untersuchen',
      '#Umfrage',
      '#Grund',
      '#ie',
      '#merken',
      '#Vokale',
      '#Texte',
      '#langes i',
      '#Zeiten',
      '#AGB',
      '#Sucht',
      '#Konfliktgespräche',
      '#Lösung',
      '#vergrößern',
      '#Multiplizieren',
      '#Tausend',
      '#Darstellung',
      '#Typen',
      '#Sachaufgabe',
      '#schriftlich',
      '#Umfang',
      '#schwer',
      '#rechnen',
      '#mit',
      '#rechter',
      '#Anleitung',
      '#Rätsel',
      '#Datenschutz',
      '#Internetviren',
      '#Analyse',
      '#Entwicklung',
      '#Berechnen',
      '#lösen',
      '#Sachaufgaben',
      '#Durchmesser',
      '#gestreckter',
      '#Quadrat',
      '#einsetzen',
      '#Textaufgabe',
      '#Bruchrechnen',
      '#ausrechnen',
      '#b',
      '#Brüche',
      '#Zahlen',
      '#Brüche dividieren',
      '#d',
      '#Bruch',
      '#arten',
      '#typen',
    ],
    link: 'https://www.catlux.de/proben/mittelschule/klasse-6',
    sourceType: 'catlux',
    isCustom: false,
    learningType: 'Article',
  },
  {
    id: '046e21fe-2a9b-47a8-9a1c-9d400d48ff9d',
    name: 'Die Einführung der sechsstufigen Realschule in Bayern',
    tags: [
      '#aufteilen',
      '#ungleich',
      '#unterscheiden',
      '#Einführung',
      '#Ablesen',
      '#diskutieren',
      '#getrennt',
      '#ablesen',
      '#Wortherkunft',
      '#ih',
      '#Diskutieren',
      '#Unterschied das',
      '#gleichseitig',
      '#Analyse',
      '#typen',
      '#Durchschnitt',
      '#Typen',
      '#Mittelwert',
    ],
    link: 'https://www.ifo.de/DocDL/ifosd_2013_03_4.pdf',
    sourceType: 'ifo',
    isCustom: false,
    learningType: 'Video',
  },
  {
    id: '0f69780e-43ae-4392-9c5d-75182d572b33',
    name: 'Darstellung',
    tags: ['#Daten', '#Diagramm', '#ablesen', '#Tabelle', '#zeichnen', '#Tabelle', '#Diagramm'],
    link: 'http://www.realmath.de/Neues/Klasse6/grundwissen/diagramm.html',
    sourceType: 'Realmath',
    isCustom: true,
    learningType: 'Exercise',
  },
  {
    id: '045c6479-551d-4183-bfda-09633dc30634',
    name: 'Teste dich: KLASSENARBEIT über Brüche – Mathe Klasse 6',
    tags: [
      '#Zeichnung',
      '#l',
      '#eintragen',
      '#zuerst',
      '#Bruchzahlen',
      '#Positive',
      '#erkennen',
      '#Beziehung',
      '#Gramm',
      '#einfach',
      '#gemischt',
      '#beide',
      '#nächste Zahl',
      '#einsetzen ausrechnen',
      '#Seiten',
      '#positiv',
      '#Geldwert',
      '#vor',
      '#ganze',
      '#Brüche eintippen',
      '#aufteilen',
      '#dreidimensional',
      '#schwierig',
      '#richtig',
      '#Arbeitsblatt',
      '#Skizze',
      '#zwei',
      '#wichtig',
      '#malrechnen',
      '#viertel',
      '#Schritte',
      '#durch',
      '#darstellen',
      '#malnehmen',
      '#gemischte',
      '#Test',
      '#Natürliche',
      '#Multiplikation; anwenden',
      '#Haus',
      '#Nenner',
      '#Kilo',
      '#anwenden',
      '#subtrahieren. Nenner',
      '#Angaben',
      '#anschauen',
      '#dem',
      '#achtel',
      '#Größen',
      '#nach',
      '#Einführung',
      '#Viertel',
      '#Teile',
      '#Ablesen',
      '#Länge',
      '#sehr',
      '#Zahl',
      '#zu',
      '#echt',
      '#viele',
      '#Ergebnis',
      '#Warum',
      '#Bruchteil',
      '#drei',
      '#lassen',
      '#unten',
      '#verwenden',
      '#Sachrechnen',
      '#Ergebnisse',
      '#Umwandlung',
      '#Anwenden',
      '#drittel',
      '#Multiplikation',
      '#y',
      '#ablesen',
      '#minus',
      '#Meter',
      '#addieren',
      '#m',
      '#teilen',
      '#Division',
      '#Textaufgaben',
      '#x',
      '#umrechnen',
      '#cm',
      '#geteilt',
      '#verschiedene',
      '#berechnen',
      '#mal',
      '#Addition',
      '#Stunde',
      '#größer',
      '#Tausend',
      '#Stellen',
      '#errichten',
      '#schwer',
      '#rechnen',
      '#mit',
      '#Umkehrbruch',
      '#rechter',
      '#Name',
      '#Berechnen',
      '#lösen',
      '#Brüche Grundwissen',
      '#Sachaufgaben',
      '#Minute',
      '#umwandeln',
      '#Anteile',
      '#Uhr',
      '#einsetzen',
      '#benennen',
      '#ausrechnen',
      '#Zahlen',
      '#d',
      '#zeichnen',
      '#Namen',
      '#aufstellen',
    ],
    link: 'https://www.youtube.com/watch?v=AQ9p5J2whIk',
    sourceType: 'youtube',
    isCustom: false,
  },
  {
    id: '08099b4b-38c4-4c1d-87c1-dd03248a566e',
    name: 'Mittelschule - 9 - Mathematik - Fachlehrpläne - LehrplanPLUS',
    tags: [
      '#Würfelgebäude',
      '#umgekehrt',
      '#Negative',
      '#Cent',
      '#Verbindungsgesetz',
      '#Name',
      '#zuerst',
      '#Tarif',
      '#x Gleichung',
      '#nächste Zahl',
      '#Typ',
      '#Punkte',
      '#ganze',
      '#Rechenzeichen',
      '#räumliches',
      '#Längen',
      '#beide',
      '#Zusammengesetzte',
      '#Rätsel',
      '#Dezimalbruch',
      '#Gramm',
      '#Modalwert',
      '#aufteilen',
      '#ct',
      '#Planfigur',
      '#gleichseitig',
      '#Halbgerade',
      '#Drache',
      '#Linie',
      '#Zahlenfolge',
      '#eintragen',
      '#Zeichnung',
      '#Anleitung',
      '#Euro',
      '#Quader',
      '#Zahlengeraden',
      '#Raummaße',
      '#Basiswinkel',
      '#negativ',
      '#l',
      '#dreidimensional',
      '#Zweisatz',
      '#casio',
      '#Spannweite',
      '#abrunden',
      '#Lineal',
      '#Koordinaten',
      '#Pizza',
      '#Kommazahlen',
      '#gleichschenklig',
      '#Planskizze',
      '#Ursprung',
      '#Benennung',
      '#€',
      '#Hochwertachse',
      '#gemischt',
      '#Steigung',
      '#gleichseitig. Gleichschenklig',
      '#Vorrangregel',
      '#Variablen',
      '#Rechenregel',
      '#rechtwinklig',
      '#Zentralwert',
      '#Zahlenreihen',
      '#Text Grundbegriffe',
      '#Minimalwert',
      '#erweitern',
      '#Zahlenrätsel',
      '#ml',
      '#Rangliste',
      '#Funktion',
      '#Liter und Milliliter',
      '#Geometrie',
      '#erstellen',
      '#Runden',
      '#Diagonale',
      '#Würfel',
      '#Dreiecke',
      '#Kommutativgesetz',
      '#Umkehraufgaben',
      '#Rechengesetz',
      '#Viereck',
      '#einfach',
      '#TI-30',
      '#Beschriftung',
      '#unregelmäßig',
      '#Mantel',
      '#rechter',
      '#Kathete',
      '#Kilogramm und Tonne',
      '#beschriften',
      '#Zahlenpaar',
      '#Rechenarten',
      '#Kommazahlen multiplizieren',
      '#Positive',
      '#einzeichnen',
      '#Raster',
      '#Winkeltypen',
      '#Stellenwerttafel',
      '#Hunderter',
      '#Vielfache',
      '#gleichnamig',
      '#Zehntel',
      '#Einführung',
      '#Sachrechnen',
      '#Haus',
      '#Angaben',
      '#Tausendstel',
      '#Warum',
      '#Koordinate',
      '#Viertel',
      '#Definition',
      '#Länge',
      '#nach',
      '#wichtig',
      '#Zähler',
      '#mittel',
      '#Trapez',
      '#drittel',
      '#viele',
      '#ungleich',
      '#Größen',
      '#Ablesen',
      '#anwenden',
      '#Anwendung',
      '#Kanten',
      '#viertel',
      '#falten',
      '#Modell',
      '#Fachbegriffe',
      '#Ergebnis',
      '#Platzhalteraufgaben',
      '#Schmetterlingsmethode',
      '#Divisor',
      '#Zahl',
      '#anordnen',
      '#visuell',
      '#kritisch',
      '#Arten',
      '#Bruchteil',
      '#Stammbruch',
      '#runden',
      '#malnehmen',
      '#darstellen',
      '#einordnen',
      '#Stellenwert',
      '#Atemlos',
      '#Kommazahl',
      '#Grundrechenarten',
      '#Lernpfad',
      '#Gegenzahl',
      '#gemischte',
      '#Nenner',
      '#überflüssige',
      '#Zehnerbruch',
      '#Ecke',
      '#verwenden',
      '#Kante',
      '#Darstellungen',
      '#Stadtplan',
      '#achtel',
      '#Quotient',
      '#anschauen',
      '#besondere',
      '#lassen',
      '#Kilo',
      '#Hundertstel',
      '#Schritte',
      '#Teile',
      '#unten',
      '#richtig',
      '#ergänzen',
      '#sehr',
      '#Song',
      '#Tank',
      '#Umwandlung',
      '#Arbeitsblatt',
      '#malrechnen',
      '#Tanken',
      '#durch',
      '#der Vierecke',
      '#Multiplikation; anwenden',
      '#betrachten',
      '#Skizze',
      '#überflüssig',
      '#drei',
      '#zwei',
      '#Ergebnisse',
      '#zu',
      '#unecht',
      '#Reihenfolge',
      '#Kommastellen',
      '#dem',
      '#Liter',
      '#Bilder',
      '#Rechenfrage',
      '#veranschaulichen',
      '#Anwenden',
      '#Sechseck',
      '#Papier',
      '#echt',
      '#Wortspeicher',
      '#unwichtig',
      '#sechstel',
      '#Flächeninhalte berechnen',
      '#km',
      '#multiplizieren',
      '#WSW',
      '#Seiten benennen',
      '#Flächeninhalt berechnen',
      '#Oberfläche',
      '#Grundwert berechnen',
      '#Dreiecke benennen',
      '#interpretieren',
      '#Geobrett',
      '#Fragebogen',
      '#Oberflächeninhalt berechnen',
      '#Oberflächeninhalt',
      '#Rechenregeln',
      '#teilen',
      '#mal',
      '#Quadratmillimeter',
      '#Zusammengesetzte Fläche berechnen',
      '#Parallelogramm',
      '#Punkt',
      '#vereinfachen',
      '#Prozentsatz Begriffe',
      '#Häufigkeitstabelle',
      '#Daten',
      '#Flächen berechnen',
      '#addieren',
      '#plus',
      '#konstruieren',
      '#Oberflächeninhalt Prismen',
      '#Grundwert',
      '#Säulendiagramm',
      '#Winkel berechnen',
      '#Flächen aufteilen',
      '#halbschriftlich',
      '#Dreiecksarten',
      '#cm²',
      '#ablesen',
      '#Formeln auflösen',
      '#Volumen',
      '#Gleichungen',
      '#Multiplikation',
      '#planen',
      '#umrechnen',
      '#Klammern auflösen',
      '#Dezimeter',
      '#Zusammenhang',
      '#dividieren',
      '#gleiche',
      '#Pfeil',
      '#Dreiecksnamen',
      '#geteilt',
      '#Tools',
      '#Figuren',
      '#Grundbegriffe',
      '#Prozentsatz berechnen',
      '#Streifenregel',
      '#Flächeneinheiten',
      '#Netz',
      '#m',
      '#Bezeichnungen',
      '#verschiedene',
      '#Schrägbild',
      '#Prozent',
      '#Schrägbilder zeichnen',
      '#Klammer',
      '#Division',
      '#Seiten bezeichnen',
      '#Strecke',
      '#Textaufgaben',
      '#Innenwinkel',
      '#Winkel',
      '#Dreiecke bezeichnen',
      '#Quadratzentimeter',
      '#cm',
      '#Wertetabelle',
      '#minus',
      '#Terme',
      '#Gerade',
      '#sammeln',
      '#y',
      '#Umrechnungszahl',
      '#Grundbegriffe der Geometrie',
      '#Außenwinkel',
      '#Diagramm',
      '#Variable',
      '#Diagrammarten',
      '#Dreisatz',
      '#x',
      '#Schaubilder',
      '#dm',
      '#SSW',
      '#Flächenformel',
      '#Glieder',
      '#berechnen',
      '#PC',
      '#Term',
      '#Zentimeter',
      '#subtrahieren',
      '#Prozentwert berechnen',
      '#Millimeter',
      '#Vorzeichen',
      '#Dreiecke beschriften',
      '#Dreiecksformen',
      '#SWS',
      '#mm²',
      '#Tausend',
      '#Sekunde',
      '#Gleichungen lösen',
      '#arten',
      '#Netz zeichnen',
      '#Gleichung',
      '#aufstellen',
      '#Deckfläche',
      '#lösen',
      '#Textaufgabe',
      '#Höhe',
      '#Dreieck',
      '#Million',
      '#Minute',
      '#Balken',
      '#benennen',
      '#Anteile',
      '#Sachaufgaben',
      '#gestreckter',
      '#einsetzen',
      '#Dezimalzahl',
      '#messen',
      '#spitzer',
      '#Winkelnamen',
      '#Konstruktion',
      '#Typen',
      '#Körpernetz',
      '#Durchmesser',
      '#Kreis',
      '#errichten',
      '#Darstellung',
      '#Lot',
      '#Fläche berechnen',
      '#Stellen',
      '#Übertrag',
      '#Zirkel',
      '#Sachaufgabe',
      '#Diagramme',
      '#Gleichungen aus Sachaufgaben',
      '#Subtraktion',
      '#auflösen',
      '#Grundlinie',
      '#Kehrwert',
      '#Kommandostrich',
      '#Prozentsatz',
      '#Fläche',
      '#kanten',
      '#Zahlen',
      '#Grad',
      '#Winkelarten',
      '#Kehrwert bilden',
      '#Zahlengerade',
      '#Umgekehrt',
      '#Linien',
      '#Geraden',
      '#Raute',
      '#Rechtswertachse',
      '#positiv',
      '#Gitterfeld',
      '#Seiten',
      '#Hypotenuse',
      '#Rauminhalt',
      '#Säule',
      '#erkennen',
      '#Einheiten',
      '#Rastermethode',
      '#Maßstab berechnen',
      '#vor',
      '#Punkte eintragen',
      '#Beziehung',
      '#einsetzen ausrechnen',
      '#Flächen',
      '#Nachfolger',
      '#vergrößern',
      '#Radius',
      '#Stunde',
      '#Vollwinkel',
      '#Grundbegriffe benennen',
      '#Flächeninhalt',
      '#zeichnen',
      '#Zahlenstrahl',
      '#Flächenformel umstellen',
      '#Gleichungen aufstellen',
      '#schriftlich',
      '#schwer',
      '#ausrechnen',
      '#Addition',
      '#stumpfer',
      '#parallel',
      '#Flächenberechnung',
      '#positive Zahlen',
      '#Umkehrbruch',
      '#rechnen',
      '#Mittelpunkt',
      '#Grundfläche berechnen',
      '#Senkrechte',
      '#Geodreieck',
      '#Billion',
      '#mit',
      '#Rechteck',
      '#Bruch',
      '#Grundfläche',
      '#umformen',
      '#untereinander',
      '#Maßstab',
      '#Umkehraufgabe',
      '#Verbindung',
      '#Quadrat',
      '#typen',
      '#Vorgänger',
      '#r',
      '#senkrecht',
      '#Ecken',
      '#Modus',
      '#Klammern',
      '#Körperinhalt',
      '#Berechnen',
      '#Umfang',
      '#Schaubild',
      '#größer',
      '#ÄquivalenZumformung',
      '#kleiner',
      '#umwandeln',
      '#Variablen zusammenfassen',
      '#arithmetisches',
      '#Multiplizieren',
      '#Uhr',
      '#Mantelfläche',
      '#d',
      '#b',
      '#Mittelwert',
    ],
    link: 'https://www.lehrplanplus.bayern.de/fachlehrplan/mittelschule/9/mathematik/mittlere-reife-klasse',
    sourceType: 'bayern',
    isCustom: false,
  },
  {
    id: '01411f71-c406-4fad-aa73-21332e7a57bd',
    name: '▷ Proben Mathematik Klasse 8 Mittelschule | Catlux',
    tags: [
      '#rechter',
      '#einfach',
      '#Anleitung',
      '#Kopfgeometrie',
      '#Verständnis',
      '#schwierig',
      '#Sachrechnen',
      '#mittel',
      '#nach',
      '#Ablesen',
      '#besondere',
      '#zwei',
      '#drei',
      '#Test',
      '#Arten',
      '#sehr',
      '#dem',
      '#Warum',
      '#zu',
      '#kritisch',
      '#richtig',
      '#ablesen',
      '#konstruieren',
      '#Term',
      '#x',
      '#Gleichungen',
      '#Textaufgaben',
      '#m',
      '#Fragebogen',
      '#auflösen nach',
      '#Variable',
      '#auflösen',
      '#lösen',
      '#Konstruktion',
      '#typen',
      '#b',
      '#Typen',
      '#Kommandostrich',
      '#Gleichungen aufstellen',
      '#aufstellen',
      '#d',
      '#x Gleichung',
      '#gemischt',
      '#Gramm',
      '#mit',
      '#Sachaufgaben',
      '#Gleichung',
      '#arten',
      '#Gleichungen aus Sachaufgaben',
      '#ÄquivalenZumformung',
      '#Stellen',
    ],
    link: 'https://www.catlux.de/proben/mittelschule/klasse-8/mathematik',
    sourceType: 'catlux',
    isCustom: false,
  },
  {
    id: '030e3a53-e37c-40d1-8da5-a31c2e67fc06',
    name: '5. Klasse Mathe Schulaufgaben & Übungen - Gymnasium',
    tags: [
      '#Geldwert',
      '#Terme aufstellen',
      '#Winkelsumme',
      '#Zahlen runden',
      '#Flächen',
      '#erstellen',
      '#Rechenarten',
      '#Punkte',
      '#Geraden',
      '#gemischt',
      '#Kommazahlen',
      '#negativ',
      '#Säulendiagramm zeichnen',
      '#Rechenzeichen',
      '#Achsen',
      '#Halbgerade',
      '#Beziehung',
      '#einzeichnen',
      '#Dreiecke',
      '#nächste Zahl',
      '#einfach',
      '#Kurvendiagramm zeichnen',
      '#Gitterfeld',
      '#abrunden',
      '#Negative',
      '#Umwandlung',
      '#darstellen',
      '#Gegenzahl',
      '#Grundrechenarten',
      '#Koordinate',
      '#runden',
      '#natürliche Zahlen',
      '#Arten',
      '#Dezimalzahlen',
      '#der Vierecke',
      '#verwenden',
      '#Platzhalteraufgaben',
      '#Sachrechnen',
      '#Achsensymmetrie',
      '#Zahl',
      '#Natürliche',
      '#Anwenden',
      '#Vierecke',
      '#Vielfache',
      '#anordnen',
      '#anwenden',
      '#gemischte',
      '#Ergebnisse',
      '#Ablesen',
      '#anschauen',
      '#Arbeitsblatt',
      '#besondere',
      '#Rechengesetze',
      '#Balkendiagramm',
      '#Terme',
      '#Lot fällen',
      '#Glieder',
      '#Seiten benennen',
      '#Winkel benennen',
      '#Flächenformel',
      '#Pfeildiagramm',
      '#Klammern auflösen',
      '#Koordinatensystem',
      '#Dreiecke benennen',
      '#umrechnen',
      '#Diagramm',
      '#Prozent',
      '#Strecke',
      '#Körper',
      '#Winkel bezeichnen',
      '#Außenwinkel',
      '#Innenwinkel',
      '#Seiten bezeichnen',
      '#Punkt',
      '#Winkel berechnen',
      '#Diagrammarten',
      '#Säulendiagramm',
      '#ablesen',
      '#Kurvendiagramm',
      '#konstruieren',
      '#Dreiecke Vierecke berechnen',
      '#Kreisdiagramm',
      '#Textaufgaben',
      '#Winkel',
      '#Flächen aufteilen',
      '#Liniendiagramm',
      '#Figuren',
      '#Dreiecke zeichnen',
      '#Oberflächeninhalt',
      '#Parallelogramm',
      '#Rechenregeln',
      '#Flächen berechnen',
      '#Flächeninhalt berechnen',
      '#Gerade',
      '#Term',
      '#km',
      '#Oberfläche',
      '#auflösen nach',
      '#Klammer',
      '#verschiedene',
      '#Oberflächeninhalt berechnen',
      '#negative Zahlen',
      '#Balkendiagramm erstellen',
      '#einsetzen',
      '#Grundfläche',
      '#umformen',
      '#rechnen',
      '#Grundfläche berechnen',
      '#Verbindung',
      '#zeichnen',
      '#Lot',
      '#Klammern',
      '#senkrecht',
      '#Uhr',
      '#errichten',
      '#Dreieck',
      '#Winkeltypen',
      '#eintragen',
      '#Liniendiagramm erstellen',
      '#Koordinaten',
      '#Punkte eintragen',
      '#Kurvendiagramm erstellen',
      '#Rechengesetz',
      '#aufrunden',
      '#Längen',
      '#Gramm',
      '#Säulendiagramm erstellen',
      '#Liniendiagramm zeichnen',
      '#Einheiten',
      '#Seiten',
      '#Massen umrechnen',
      '#einsetzen ausrechnen',
      '#Runden',
      '#ganze Zahlen',
      '#Sachaufgaben',
      '#Kreis',
      '#Kreise',
      '#Balkendiagramm zeichnen',
      '#Sachaufgabe',
      '#benennen',
      '#Fläche',
      '#Flächenberechnung',
      '#Quadrat',
      '#Balken',
      '#lösen',
      '#Flächeninhalt',
      '#kleiner',
      '#aufstellen',
      '#messen',
      '#Schaubild',
      '#Viereck',
      '#Textaufgabe',
      '#Diagramme',
      '#umwandeln',
      '#Umfang',
      '#auflösen',
      '#Zahlen',
      '#arten',
      '#Winkelarten',
      '#Mantelfläche',
      '#Senkrechte',
      '#ausrechnen',
    ],
    link: 'https://einsundzwei.de/gymnasium/5-klasse-gymnasium/schulaufgabe-mathematik-gymnasium-5',
    sourceType: 'einsundzwei',
    isCustom: false,
  },
  {
    id: '04f341e2-273b-437c-b361-095219fe8518',
    name: 'Materialpaket MATHEMATIK Klasse 5 *Drei ... - eduki',
    tags: [
      '#Zahlen runden',
      '#Punkte',
      '#Rastermethode',
      '#beide',
      '#Quotient',
      '#Arten',
      '#Divisor',
      '#Fachbegriffe',
      '#Grundrechenarten',
      '#drei',
      '#anordnen',
      '#Zahl',
      '#Ablesen',
      '#Division',
      '#Begriffe',
      '#x',
      '#ablesen',
      '#Zahlen',
      '#Namen',
      '#Rätsel',
      '#Zahlenrätsel',
      '#Raster',
      '#Name',
      '#untereinander',
    ],
    link: 'https://eduki.com/de/material/709713/materialpaket-mathematik-klasse-5-drei-leisungsnachweise-mittelschule-bayern-lehrplanplus-naturliche-zahlen-grundrechenarten-fachbegriffe',
    sourceType: 'eduki',
    isCustom: false,
  },
  {
    id: '0dd6f1c6-7331-4add-a414-326faea52c75',
    name: 'Diagramme',
    tags: [
      '#Daten',
      '#auswerten',
      '#Liniendiagramm',
      '#Diagramm',
      '#ablesen',
      '#beschreiben',
      '#beschreiben',
      '#beschreiben',
      '#Diagramm',
    ],
    link: 'https://learningapps.org/10323916',
    sourceType: 'Learning Apps',
    isCustom: true,
    learningType: 'Video',
  },
  {
    id: '0ff37baf-ccde-4594-96b5-6a38ddb5f198',
    name: 'Mittelschule M-Zug (Themenbereich) - lernen mit Serlo!',
    tags: [
      '#Terme aufstellen',
      '#Hunderter',
      '#Dezimalbruch',
      '#Massen umrechnen',
      '#aufteilen',
      '#Geometrie',
      '#Umkehraufgaben',
      '#Zahlengeraden',
      '#Temperatur',
      '#Warum',
      '#Definition',
      '#Dezimalbrüche',
      '#unten',
      '#mittel',
      '#viele',
      '#Größen',
      '#Anwenden',
      '#Zahl',
      '#Umwandlung',
      '#verwenden',
      '#malrechnen',
      '#anwenden',
      '#Test',
      '#Bilder',
      '#Teile',
      '#veranschaulichen',
      '#durch',
      '#zu',
      '#dem',
      '#Angaben',
      '#Handlung',
      '#Körper',
      '#Lot fällen',
      '#teilen',
      '#Terme',
      '#Begriffe',
      '#Grundbegriffe der Geometrie',
      '#Terme Gleichungen',
      '#Meter',
      '#Flächeninhalt berechnen',
      '#m',
      '#km',
      '#berechnen',
      '#Prozent',
      '#Flächen berechnen',
      '#Flächen aufteilen',
      '#Gleichungen',
      '#Prozentrechnung',
      '#Punkt',
      '#dividieren',
      '#verschiedene',
      '#plus',
      '#ablesen',
      '#Bezeichnungen',
      '#Term',
      '#rationale Zahlen',
      '#was ist wichtig',
      '#Einfügen',
      '#aufstellen',
      '#Inhalt',
      '#Gleichung',
      '#Fläche',
      '#Quadrat',
      '#Deckfläche',
      '#Berechnen',
      '#Senkrechte',
      '#Rationale Zahlen',
      '#Grundfläche',
      '#Zahlen',
      '#Seiten',
      '#Potenzen',
      '#ganze',
      '#Flächen',
      '#Stellen',
      '#Dezimalzahl',
      '#ausrechnen',
      '#Prozentrechnen',
      '#rechnen',
      '#mit',
      '#Tausend',
      '#umwandeln',
    ],
    link: 'https://de.serlo.org/mathe/16359/mittelschule-m-zug',
    sourceType: 'serlo',
    isCustom: false,
  },
] as MaterialLink[];
