export default {
  student: {
    login: '/login',
    forgotPassword: '/forgot-password',
    resetPassword: '/reset-password/:token',
    register: '/register',
    registerName: '/register/name',
    registerEmail: '/register/email',
    registerPassword: '/register/password',
    registerBirthday: '/register/birthday',
    registerSchool: '/register/school',
    registerSubjects: '/register/subjects',
    home: '/home',
    focusTime: '/focus-time',
    lookUp: '/look-up',
    summary: '/summary',
    study: '/study-individual',
    studyDiary: '/study-diary',
    profile: '/profile',
    dashboard: '/dashboard',
    studyCards: '/study-cards',
    studyCardsSet: '/study-cards/:id',
    studyCardsCreate: '/study-cards-create',
    studyCardsDiscover: '/study-cards-discover',
    studyCardsGeneralKnowledge: '/study-cards-general-knowledge',
    studyCardsDiscoverSet: '/study-cards-discover/:id',
    studyCardsEditSet: '/study-cards-edit/:id',
    studyCardsLearnOverview: '/study-cards-learn/overview/:id',
    studyCardsLearnSession: '/study-cards-learn/session',
    studyNotes: '/study-notes',
    search: '/search',
    ido: '/ido',
  },
};
